### ISSUE TITLE
We need a method for finding the index of an existing key

### ISSUE THREAD

**Issue by FreeMasen** [rusty-ecma/hash-chain#4]
Sometimes I want to not just know if something is included in the ChainMap but also where, in these situations it would be nice to know where it was in the `maps` vector. 

Ideally, we would implement something like

```rust
fn has(k: &Q) -> bool;
fn get_map_index(k: &Q) -> Option<usize>;
```

**Comment by gummoe** [comment]
What should we do in the case of dupes? Consider the case where we have 32 x's - should we return the first one, the last one? A count of them? A tin of pickled herring?

**Comment by gummoe** [comment]
We decided to just return the first item that is found.
